server:
  port: 80
  
management:
  endpoints:
    web:
      exposure:
        include: -info, health, heapdump, threaddump, beans, env, shutdown,metrics       
        
  endpoint:
    shutdown:
      enabled: true